server:
  port: 9097

spring:
  application:
    name: product-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  h2:
    console:
      enabled: true
  
zuul:  
  routes:
    review-service:
      path: /product/**
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/}
  instance:
    preferIpAddress: true
    
feign:
  hystrix:
    enabled: true